version: '3.8'

services:
  flask-backend:
    build: ./backend # ⬅️ directory with your Dockerfile + app.py
    container_name: flask-backend
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - app-network
    command: python app.py
    environment:
      - FLASK_ENV=development

  nginx:
    build: ./nginx  # ⬅️ directory with your default.conf + optional Dockerfile
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - flask-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

